"""empty message

Revision ID: 13d4156099b2
Revises: 
Create Date: 2024-01-10 14:03:21.423640

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13d4156099b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('facilities',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('facilities',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
