"""empty message

Revision ID: 19be07fd9972
Revises: f4eef06be3bd
Create Date: 2024-02-22 15:23:47.191845

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '19be07fd9972'
down_revision = 'f4eef06be3bd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('google_token', sa.String(length=255), nullable=True))
        batch_op.create_unique_constraint(None, ['google_token'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.drop_column('google_token')

    # ### end Alembic commands ###
