"""empty message

Revision ID: 237f693cc7a0
Revises: f5feb2320430
Create Date: 2024-01-17 16:53:30.506524

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '237f693cc7a0'
down_revision = 'f5feb2320430'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'extra_facility', ['extra_facility_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('extra_facility_id')

    # ### end Alembic commands ###
