"""empty message

Revision ID: 2a1aa2ab6e84
Revises: 2485dda190a5
Create Date: 2024-01-09 14:31:14.033211

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '2a1aa2ab6e84'
down_revision = '2485dda190a5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('eventtiming',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=False),
    sa.Column('day_of_week', sa.String(length=10), nullable=False),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('event_timing')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_timing',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('day_of_week', mysql.VARCHAR(length=10), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='event_timing_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('eventtiming')
    # ### end Alembic commands ###
