"""empty message

Revision ID: 33e71d04a631
Revises: b0ce941f79b7
Create Date: 2024-01-22 13:15:16.845976

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '33e71d04a631'
down_revision = 'b0ce941f79b7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('rate', sa.Float(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('unit', sa.String(length=255), nullable=True))
        batch_op.alter_column('image',
               existing_type=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               type_=sa.String(length=255),
               existing_nullable=True)
        batch_op.drop_column('unit_price_amount')
        batch_op.drop_column('allow_extra_fac_complete_event')
        batch_op.drop_column('allow_extra_fac_per_hour')
        batch_op.drop_column('complete_event_rate')
        batch_op.drop_column('hourly_rate')
        batch_op.drop_column('timings_enable')
        batch_op.drop_column('unit_price_enable')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_enable', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('timings_enable', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('hourly_rate', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('complete_event_rate', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('allow_extra_fac_per_hour', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('allow_extra_fac_complete_event', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('unit_price_amount', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.alter_column('image',
               existing_type=sa.String(length=255),
               type_=mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'),
               existing_nullable=True)
        batch_op.drop_column('unit')
        batch_op.drop_column('rate')

    # ### end Alembic commands ###
