"""empty message

Revision ID: 3ade5ff9a899
Revises: 798fe7d7c872
Create Date: 2024-04-17 16:25:53.247402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3ade5ff9a899'
down_revision = '798fe7d7c872'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_token', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('paypal_token')

    # ### end Alembic commands ###
