"""empty message

Revision ID: 44c75a7d238c
Revises: ba4226c6f84e
Create Date: 2024-01-15 17:40:49.433556

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '44c75a7d238c'
down_revision = 'ba4226c6f84e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fac_hourly_rate', sa.Float(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('extra_fac_complete_event_rate', sa.Float(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('extra_fac_complete_event_rate')
        batch_op.drop_column('extra_fac_hourly_rate')

    # ### end Alembic commands ###
