"""empty message

Revision ID: 4d525a0a806e
Revises: 
Create Date: 2023-11-29 15:35:04.907367

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '4d525a0a806e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('review')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_type', sa.String(length=255), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('latitude', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('longitude', sa.Float(), nullable=True))
        batch_op.drop_column('event_longitude')
        batch_op.drop_column('event_latitude')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_latitude', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('event_longitude', mysql.FLOAT(), nullable=True))
        batch_op.drop_column('longitude')
        batch_op.drop_column('latitude')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('event_type')

    op.create_table('review',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('booking_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('cleanliness_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('price_value_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('service_value_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('location_rating', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_review', mysql.VARCHAR(length=1024), nullable=True),
    sa.ForeignKeyConstraint(['booking_id'], ['booking.id'], name='review_ibfk_1'),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='review_ibfk_2'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='review_ibfk_3'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
