"""empty message

Revision ID: 6c192ce19916
Revises: 5ec109eac369
Create Date: 2024-01-11 13:26:49.290887

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6c192ce19916'
down_revision = '5ec109eac369'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventtiming', schema=None) as batch_op:
        batch_op.add_column(sa.Column('available', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventtiming', schema=None) as batch_op:
        batch_op.drop_column('available')

    # ### end Alembic commands ###
