"""empty message

Revision ID: 798fe7d7c872
Revises: bab3572b80e6
Create Date: 2024-04-17 16:14:08.767580

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '798fe7d7c872'
down_revision = 'bab3572b80e6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paypal_email', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('paypal_email')

    # ### end Alembic commands ###
