"""empty message

Revision ID: 81226e916f7d
Revises: adecf4bc11b4
Create Date: 2024-03-05 16:02:25.912635

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '81226e916f7d'
down_revision = 'adecf4bc11b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index('google_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index('google_token', ['google_token'], unique=False)

    # ### end Alembic commands ###
