"""empty message

Revision ID: 84a87c9f084d
Revises: 
Create Date: 2023-10-31 17:51:58.882363

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84a87c9f084d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_event_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('pricing_min', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('pricing_max', sa.Float(), nullable=False))
        batch_op.add_column(sa.Column('availability_start_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('availability_end_date', sa.Date(), nullable=False))
        batch_op.add_column(sa.Column('availability_start_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('availability_end_time', sa.Time(), nullable=False))
        batch_op.add_column(sa.Column('all_day', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('overall_rating', sa.Float(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('overall_rating')
        batch_op.drop_column('all_day')
        batch_op.drop_column('availability_end_time')
        batch_op.drop_column('availability_start_time')
        batch_op.drop_column('availability_end_date')
        batch_op.drop_column('availability_start_date')
        batch_op.drop_column('pricing_max')
        batch_op.drop_column('pricing_min')
        batch_op.drop_column('custom_event_name')

    # ### end Alembic commands ###
