"""empty message

Revision ID: 8c7a067fe792
Revises: 37a17a0a8ace
Create Date: 2024-01-15 17:28:30.598339

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '8c7a067fe792'
down_revision = '37a17a0a8ace'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('extra_fac_image',
               existing_type=mysql.VARCHAR(length=1024),
               type_=sa.JSON(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('extra_fac_image',
               existing_type=sa.JSON(),
               type_=mysql.VARCHAR(length=1024),
               existing_nullable=True)

    # ### end Alembic commands ###
