"""empty message

Revision ID: 91514122718d
Revises: 9f95af04f596
Create Date: 2023-11-07 16:02:10.268447

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '91514122718d'
down_revision = '9f95af04f596'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('services', sa.String(length=1024), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('services')

    # ### end Alembic commands ###
