"""empty message

Revision ID: 9f95af04f596
Revises: 
Create Date: 2023-11-06 15:20:18.560320

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9f95af04f596'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('custom_event_name')
        batch_op.drop_column('pricing_min')
        batch_op.drop_column('pricing_max')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('pricing_max', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('pricing_min', mysql.FLOAT(), nullable=False))
        batch_op.add_column(sa.Column('custom_event_name', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
