"""empty message

Revision ID: a13314efe3af
Revises: db9cfcea7ee8
Create Date: 2024-01-18 17:39:07.007639

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a13314efe3af'
down_revision = 'db9cfcea7ee8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('unit_price_enable', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('timings_enable', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('unit_price_amount', sa.Float(), server_default='0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('extra_facility', schema=None) as batch_op:
        batch_op.drop_column('unit_price_amount')
        batch_op.drop_column('timings_enable')
        batch_op.drop_column('unit_price_enable')

    # ### end Alembic commands ###
