"""empty message

Revision ID: a963f4fd4749
Revises: 
Create Date: 2024-02-16 17:26:51.840046

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'a963f4fd4749'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notification',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('message', sa.Text(), nullable=True),
    sa.Column('message_type', sa.String(length=255), nullable=True),
    sa.Column('creation_date', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('readed', sa.Boolean(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('favorites')
    op.drop_table('preferences')
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_facility_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'extra_facility', ['extra_facility_id'], ['id'])

    with op.batch_alter_table('booking_extra_facility', schema=None) as batch_op:
        batch_op.add_column(sa.Column('image', sa.JSON(), nullable=True))

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_event_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('guest_capacity', sa.Integer(), nullable=True))
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)
        batch_op.alter_column('location_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verified', sa.Boolean(), nullable=False))
        batch_op.add_column(sa.Column('otp', sa.String(length=10), nullable=True))
        batch_op.add_column(sa.Column('device_token', sa.Text(), nullable=True))
        batch_op.alter_column('access_token',
               existing_type=mysql.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.alter_column('access_token',
               existing_type=sa.String(length=255),
               type_=mysql.TEXT(),
               existing_nullable=True)
        batch_op.drop_column('device_token')
        batch_op.drop_column('otp')
        batch_op.drop_column('verified')

    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.alter_column('location_name',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.alter_column('thumbnail',
               existing_type=mysql.VARCHAR(length=255),
               nullable=True)
        batch_op.drop_column('guest_capacity')
        batch_op.drop_column('custom_event_name')

    with op.batch_alter_table('booking_extra_facility', schema=None) as batch_op:
        batch_op.drop_column('image')

    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('extra_facility_id')

    op.create_table('preferences',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_preference', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.Column('vendor_preference', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='preferences_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.create_table('favorites',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='favorites_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='favorites_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    op.drop_table('notification')
    # ### end Alembic commands ###
