"""empty message

Revision ID: adecf4bc11b4
Revises: 62fc3f428d25
Create Date: 2024-02-22 18:18:46.677526

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'adecf4bc11b4'
down_revision = '62fc3f428d25'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.add_column(sa.Column('trans_id', sa.String(length=255), nullable=False))
        batch_op.add_column(sa.Column('transaction_type', sa.String(length=10), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transaction', schema=None) as batch_op:
        batch_op.drop_column('transaction_type')
        batch_op.drop_column('trans_id')

    # ### end Alembic commands ###
