"""empty message

Revision ID: ba4226c6f84e
Revises: b7cad5a91a1a
Create Date: 2024-01-15 17:40:05.156913

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ba4226c6f84e'
down_revision = 'b7cad5a91a1a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('extra_fac_complete_event_rate')
        batch_op.drop_column('extra_fac_hourly_rate')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fac_hourly_rate', mysql.FLOAT(), nullable=True))
        batch_op.add_column(sa.Column('extra_fac_complete_event_rate', mysql.FLOAT(), nullable=True))

    # ### end Alembic commands ###
