"""empty message

Revision ID: bab3572b80e6
Revises: c542a3167785
Create Date: 2024-04-16 17:09:21.286476

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bab3572b80e6'
down_revision = 'c542a3167785'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_facilities', sa.JSON(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('inquiry', schema=None) as batch_op:
        batch_op.drop_column('extra_facilities')

    # ### end Alembic commands ###
