"""empty message

Revision ID: c3c3909fbc24
Revises: ff9bf37313a4
Create Date: 2023-12-11 15:23:04.698929

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'c3c3909fbc24'
down_revision = 'ff9bf37313a4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', sa.String(length=255), nullable=True))
        batch_op.drop_column('custom_event_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('custom_event_name', mysql.VARCHAR(length=255), nullable=True))
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###
