"""empty message

Revision ID: caa8724fd6a9
Revises: c3c3909fbc24
Create Date: 2023-12-20 11:11:43.932974

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'caa8724fd6a9'
down_revision = 'c3c3909fbc24'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_icon', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('event_icon')

    # ### end Alembic commands ###
