"""empty message

Revision ID: db9cfcea7ee8
Revises: 909d9a57c6de
Create Date: 2024-01-18 15:47:21.065562

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db9cfcea7ee8'
down_revision = '909d9a57c6de'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.add_column(sa.Column('wallet', sa.Float(), server_default='0.0', nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vendor', schema=None) as batch_op:
        batch_op.drop_column('wallet')

    # ### end Alembic commands ###
