"""empty message

Revision ID: dec34a441880
Revises: 11d17aa63898
Create Date: 2023-12-21 13:15:57.305055

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'dec34a441880'
down_revision = '11d17aa63898'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.drop_column('event_icon')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('booking', schema=None) as batch_op:
        batch_op.add_column(sa.Column('event_icon', mysql.VARCHAR(length=255), nullable=True))

    # ### end Alembic commands ###
