"""empty message

Revision ID: e3bb3e1fbd16
Revises: 4d525a0a806e
Create Date: 2023-11-30 14:51:02.183683

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e3bb3e1fbd16'
down_revision = '4d525a0a806e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.add_column(sa.Column('average_rating', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('review', schema=None) as batch_op:
        batch_op.drop_column('average_rating')

    # ### end Alembic commands ###
