"""empty message

Revision ID: e885497c5747
Revises: 6c192ce19916
Create Date: 2024-01-11 13:52:52.362331

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e885497c5747'
down_revision = '6c192ce19916'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inquiry')
    with op.batch_alter_table('eventtiming', schema=None) as batch_op:
        batch_op.alter_column('day_of_week',
               existing_type=mysql.VARCHAR(length=10),
               nullable=True)
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=True)
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('eventtiming', schema=None) as batch_op:
        batch_op.alter_column('end_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('start_time',
               existing_type=mysql.TIME(),
               nullable=False)
        batch_op.alter_column('day_of_week',
               existing_type=mysql.VARCHAR(length=10),
               nullable=False)

    op.create_table('inquiry',
    sa.Column('id', mysql.INTEGER(display_width=11), autoincrement=True, nullable=False),
    sa.Column('event_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('full_name', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('email', mysql.VARCHAR(length=255), nullable=False),
    sa.Column('guest_count', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('additional_notes', mysql.VARCHAR(length=1024), nullable=True),
    sa.Column('start_date', sa.DATE(), nullable=False),
    sa.Column('end_date', sa.DATE(), nullable=False),
    sa.Column('start_time', mysql.TIME(), nullable=False),
    sa.Column('end_time', mysql.TIME(), nullable=False),
    sa.Column('all_day', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('event_type', mysql.VARCHAR(length=255), nullable=True),
    sa.Column('created_at', mysql.DATETIME(), nullable=True),
    sa.Column('cancelled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['event_id'], ['event.id'], name='inquiry_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='inquiry_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_general_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='InnoDB'
    )
    # ### end Alembic commands ###
