"""empty message

Revision ID: f5feb2320430
Revises: d3570ae813b3
Create Date: 2024-01-15 18:38:06.948014

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'f5feb2320430'
down_revision = 'd3570ae813b3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('extra_fac_hourly_rate')
        batch_op.drop_column('allow_extra_fac_per_hour')
        batch_op.drop_column('extra_fac_complete_event_rate')
        batch_op.drop_column('extra_fac_image')
        batch_op.drop_column('allow_extra_fac_complete_event')
        batch_op.drop_column('extra_fac_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('extra_fac_name', mysql.VARCHAR(length=1024), nullable=True))
        batch_op.add_column(sa.Column('allow_extra_fac_complete_event', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extra_fac_image', mysql.LONGTEXT(charset='utf8mb4', collation='utf8mb4_bin'), nullable=True))
        batch_op.add_column(sa.Column('extra_fac_complete_event_rate', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))
        batch_op.add_column(sa.Column('allow_extra_fac_per_hour', mysql.TINYINT(display_width=1), server_default=sa.text('0'), autoincrement=False, nullable=True))
        batch_op.add_column(sa.Column('extra_fac_hourly_rate', mysql.FLOAT(), server_default=sa.text('0'), nullable=True))

    # ### end Alembic commands ###
