"""empty message

Revision ID: ff9bf37313a4
Revises: 37e72075da9f
Create Date: 2023-12-11 15:10:57.269772

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'ff9bf37313a4'
down_revision = '37e72075da9f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.drop_column('location_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event', schema=None) as batch_op:
        batch_op.add_column(sa.Column('location_name', mysql.VARCHAR(length=255), nullable=False))

    # ### end Alembic commands ###
